### ISSUE TITLE
Parameters aren't being passed with events

### ISSUE THREAD

**Issue by yosser** [mjtischler/react-muuri#11]
Looks like the callbacks at lines 9040 and 9036 (in index.js and index.es.js) are happening without passing the event parameters.

I suggest replacing 
callback(); 
with 
callback(param1, param2);

**Comment by mjtischler** [comment]
Good catch! I'm just getting back from vacation so I'll take a gander this weekend.

**Comment by mjtischler** [comment]
I've addressed this in the most recent [release](https://github.com/mjtischler/react-muuri/releases/tag/v0.1.1-alpha). Thanks for the feedback!
