### ISSUE TITLE
Not working on Mac Safari

### ISSUE THREAD

**Issue by workboxsoftware** [mjtischler/react-muuri#19]
IGNORE THIS ISSUE.  I needed to add a polyfill for web animations. 

Works fine on Chrome and Firefox, but when I run it on Safari, the dragged box doesn't replace the other box.  It just stays wherever it is dropped.  See enclosed image.
<img width="560" alt="Screen Shot 2019-04-28 at 8 28 35 PM" src="https://user-images.githubusercontent.com/7016310/56872261-f1223b80-69f4-11e9-9874-f16d9bd637db.png">

**Comment by workboxsoftware** [comment]
This is a bug that Muuri introduced.  It works on Safari on 0.4.1 - but no releases after that.

**Comment by Fengziyin1234** [comment]
I think web animation polyfill is needed for safari

**Comment by mjtischler** [comment]
Great teamwork, folks! I'm going to close this issue but I'll update the README to remind others in case they missed the info on Muuri's site.
