### ISSUE TITLE
Best way to create templates to use in this.grid.getMethod(add, ...) ?

### ISSUE THREAD

**Issue by ghost** [mjtischler/react-muuri#20]
This might not even be an issue so let me know if I should move this over to StackOverflow. 

Using your Sample Component example I created a gridElement2 div in the render method and copied the children from your original gridElement div into it. 

I then replaced the line:

`this.grid.getMethod('remove', this.gridElement.children[0], {removeElements: true});`

with:

`this.grid.getMethod('add', this.gridElement2.children[0])`

I also added a `style={{ display: 'none' }}` to the gridElement2 div in the render. 

Doing this allowed me to sequentially add, through a button press each time, all the gridElement2's children to the MuuriGrid, i.e. add them as children to your gridElement. 

For example if you run `this.grid.getMethod('add', this.gridElement2.children[0]) `3 times
it will add the first three children of gridElement2 to the MuuriGrid, despite the fact 
they are the 0th, 1st and 2nd children of gridElement2. 

In my case I was hoping to be able to create a template and then make slight changes to it, such as changing img src, and be able to add an infinite number of these to the MuuriGrid.

I have tried the two methods below:

1. Passing a React Component to 

`this.grid.getMethod('add', <ReactComponent props={...}  />)`

This would make it easy to indefinitely add variations of a template to the Grid. It doesn't seem
to work at the moment and is possibly incompatible with react-muuri's code.  

2. This second method has worked for me in some cases but not when using img tags.  

Currently it is possible to create and use a template in the way you do through the original Muuri library. 

For example, this is a simple example using the same format as the Muuri Grid Demo, https://haltu.github.io/muuri/: 

```

ret = []

var itemElem = document.createElement('div');

var itemTemplate = ' ' +

'<div className="item">' +

     '<div className="item-content">' +

          'Test Text' +
    
     '</div>' +

'</div>' 

itemElem.innerHTML = itemTemplate;

ret.push(itemElem.firstChild);


this.grid.getMethod('add', [ret[0]]);   (react-muuri line)
```

and this works fine. 

But changing the 'Test Text' line to 

`<img src="./img/testImage.jpg" className="item-image" >`

adds a broken image URL to the React page -- while adding the <img> line works on a normal, non-React web page. 

This is possibly a result of the fact img src's are provided differently in normal HTML and in React -> I originally tried using `src={require("./img/testImage.jpg")}`
as well as 

`...src={' + require("./img/testImage.jpg") + '}...`

but neither of these worked.

I might just be doing something wrong with the src of the img tag but if not 
it may just not be possible to use imgs in a template in this way at the moment?

As a more general question is method 2 the way you recommend creating template items to use with react-muuri?

**Comment by mjtischler** [comment]
This is a really interesting problem and I'm happy to work through it with you to solve it. I have two ideas, but neither is perfect so perhaps they will merely serve to start a conversation.

Because the Muuri library exists outside of the virtual DOM (you can see this from your browser's React dev tools plugin), we need to use React in ways it wasn't necessarily intended. One idea is to use React's state to store the data for a list of items to be rendered. Take this default state for two images:

```
this.state = {
  gridChildren: [
    {
      class: 'box1',
      src: 'http://www.liberaldictionary.com/wp-content/uploads/2018/11/test-1.png'
    },
    {
      class: 'box2',
      src: 'http://www.liberaldictionary.com/wp-content/uploads/2018/12/out.png'
    }
  ]
}
```
In our render method, we would define `items` as:
```
const items = this.state.gridChildren.map((child, index) =>
  <div key={index} className={`item ${child.class}`}>
    <div className="item-content">
      <img src={child.src} alt={child.class}></img>
    </div>
  </div>
)
```
We could assign an `addImage(image)` method to a button and call:
```
this.setState({gridChildren: [...this.state.gridChildren, {
    class: image.class,
    src: image.src
  }
]}, () => {
  this.grid.getMethod('add', this.gridElement.children)
})
```
Here we're updating our state and then using `setState`'s callback function to affect the grid outside of the virtual DOM. FULL DISCLOSURE: The grid looks ugly when we do this, so perhaps we can work together to figure out a solution to the layout problems.

The second (and _cheap_) idea is to use:

```
this.grid.getMethod('add', ReactDOM.render(<MyComponent />, container)
```

I've played with this idea a bit but I've had trouble getting the grid to update as you would expect, likely because I haven't tried tying it to state yet (or, simply, it doesn't work).

**Comment by ghost** [comment]
Thanks for the reply.  I'm slightly confused about how const items is connected to the flow of trying to add a new child to gridElement/how it's connected to displaying content in gridElement - so haven't managed to get the first method working at the moment.  Do you have all the code for it? I'm only just learning React and haven't built much with it yet but when I have them working I will definitely look at both methods above and try my best to find solutions/workarounds to the problems.

**Comment by ghost** [comment]
So I managed to get it working by just adding the map function directly inside gridElement:


```
<div className="myContainer" ref={gridElement => this.gridElement = gridElement}>

        {

          this.state.gridChildren.map((item, index) => {

            return (

              <div key={index} className={`item ${item.class}`}>
                <div className="item-content">
                  <img src={item.src} alt={item.class}></img>
                </div>
              </div>

            )

          })

        }

</div>

```

You can then add elements with 


```
this.setState({
      gridChildren: [...this.state.gridChildren, {
                class: 'myBox1',
                src: 'http://www.liberaldictionary.com/wp-content/uploads/2018/11/test-1.png'
          }
      ]
}, () => {
      this.grid.getMethod('add', this.gridElement.children[index-of-new-child])
})

```
and remove them with these functions (both elementClosest & elementMatches are taken straight from the muuri grid.demo example with only a few small changes)

```

  elementMatches(element, selector) {

    var p = Element.prototype;
    return (p.matches || p.matchesSelector || p.webkitMatchesSelector || p.mozMatchesSelector || p.msMatchesSelector || p.oMatchesSelector).call(element, selector);

  }

  elementClosest(element, selector) {

    if (window.Element && !Element.prototype.closest) {
      var isMatch = this.elementMatches(element, selector);
      while (!isMatch && element && element !== document) {
        element = element.parentNode;
        isMatch = element && element !== document && this.elementMatches(element, selector);
      }
      return element && element !== document ? element : null;
    }
    else {
      return element.closest(selector);
    }

  }

  removeItem(e) {

    // This function calls elementClosest -- which subsequently calls elementMatches 

    var elem = this.elementClosest(e.target, '.item');

    this.grid.getMethod('hide', elem, {
      onFinish:  (items) => {
        var item = items[0];
        this.grid.getMethod('remove', item, { removeElements: true });
      }
    });

  }

```


The grid doesn't seem to have layout problems as you described when performing these actions.  One of the layout problems may have been a result of you using this.grid.getMethod('add', this.gridElement.children) without specifying the index of the new child? But there could be layout problems for other cases I haven't tested.  Either way it seems to be working in the way I wanted it to so thank you for the suggestion.

**Comment by kevinqiu92** [comment]
@lmb-1 how did you manage to remove the items from `this.state.gridChildren`? I keep getting a `NotFoundError` when I try to update the state in `removeItem`.

**Comment by kevinqiu92** [comment]
@lmb-1 never mind, got it to work. thanks again for sharing!
